export const CLICK_BUTTON_SUCCESS = 'CLICK_BUTTON_SUCCESS';
export const CLICK_BUTTON_FAILURE = 'CLICK_BUTTON_FAILURE';
export const CLICK_BUTTON_REQUEST = 'CLICK_BUTTON_REQUEST';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';

export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';

export const PERSIST_HYDRATE = 'persist/REHYDRATE';
